# Generated by Django 3.0.5 on 2020-09-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('cno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=15)),
                ('photo', models.ImageField(upload_to='customer_images/')),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('date_of_travel', models.DateField()),
                ('no_of_people', models.IntegerField()),
                ('message', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PackageModel',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=200)),
                ('pduration', models.CharField(max_length=10)),
                ('pdescription', models.CharField(max_length=300)),
                ('prating', models.FloatField(max_length=10)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(default=False, upload_to='package_images/')),
            ],
        ),
    ]
