# Generated by Django 3.0.5 on 2021-01-08 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='enquirymodel',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='enquirymodel',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='packagemodel',
            name='pname',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='PackDetailsModel',
            fields=[
                ('pckid', models.AutoField(primary_key=True, serialize=False)),
                ('tid', models.IntegerField()),
                ('pid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tourism.PackageModel')),
            ],
        ),
    ]
